# THIS FILE IS PART OF THE CYLC WORKFLOW ENGINE.
# Copyright (C) NIWA & British Crown (Met Office) & Contributors.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Deploy a new version of the documentation or rebuild an existing one.

# Note: All changes made to the gh-pages branch are non-destructive
#       (i.e. no force pushing) so all changes can be undone.

name: deploy

on:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        # use login shell for conda activation
        shell: bash -leo pipefail {0}
    steps:
      - name: configure python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: configure git
        uses: cylc/release-actions/configure-git@v1

      - name: checkout cylc-doc
        uses: actions/checkout@v5
        with:
          path: cylc-doc

      - name: checkout cylc-doc
        uses: actions/checkout@v5
        with:
          path: cylc-flow

      - name: debug
        run: |
          tree .